### ISSUE TITLE
Guard against repeat words

### ISSUE THREAD

**Issue by cblupo** [valeness/wordjournal#1]
It would also be nice if you could design a way to help users identify words they've already added so two entries for the same word won't be created. Simply sorting everything in alphabetical order would suffice

**Comment by valeness** [comment]
Working on it! Expect to have it up by tomorrow afternoon :D

**Comment by valeness** [comment]
Working on alphabetical order, but it will not allow you to create duplicate words anymore. (I have my SQL table set up to reject duplicate entries anyways, so it skipped my mind.) Kudos and open more issues if you need to!
